name: Build & Deploy to Firebase Hosting

on: workflow_dispatch

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Create .env file
        run: echo "REACT_APP_BUGSNAG_API_KEY=${{ secrets.BUGSNAG_API_KEY }}" > .env

      - name: Build
        run: yarn build

      - name: Upload source map to Bugsnag
        run: |
          cd build/static/js
          BUNDLE_JS=$(ls *.js)
          npx bugsnag-source-maps upload-browser \
            --api-key ${{ secrets.BUGSNAG_API_KEY }} \
            --app-version 1.0.0 \
            --bundle-url "https://admin.iyf.hu/static/js/${BUNDLE_JS}" \
            --source-map "${BUNDLE_JS}.map" \
            --bundle "${BUNDLE_JS}"
          cd ../../..

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_IYFHU_CAAF9 }}'
          projectId: iyfhu-caaf9
          channelId: live
